### ISSUE TITLE
请问装了LNMP 后可以用这个脚本安装NAIVE吗？

### ISSUE THREAD

**Issue by hkbbdx** [yonggekkk/NaiveProxy-yg#1]
提示端口冲突

**Comment by yonggekkk** [comment]
> 提示端口冲突

没装过lnmp。。。提示端口冲突那就换喽

**Comment by hkbbdx** [comment]
LNMP 会占用80 和443 端口，请问跟脚本会冲突吗？

**Comment by yonggekkk** [comment]
> LNMP 会占用80 和443 端口，请问跟脚本会冲突吗？

脚本输入的端口别设置这两个端口就行。当然证书申请建议用dns api模式了，不然续期时会与80端口冲突

**Comment by hkbbdx** [comment]
好的，谢谢！
&nbsp;


104313414
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月13日(星期一) 中午11:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yonggekkk/NaiveProxy-yg] 请问装了LNMP 后可以用这个脚本安装NAIVE吗？ (Issue #1)





  
LNMP 会占用80 和443 端口，请问跟脚本会冲突吗？
  
脚本输入的端口别设置这两个端口就行。当然证书申请建议用dns api模式了，不然续期时会与80端口冲突
