### ISSUE TITLE
debian 12 报错。

### ISSUE THREAD

**Issue by yzx1208** [yonggekkk/NaiveProxy-yg#3]
SHELL=/bin/bash
INVOCATION_ID=10ef7c34b68f4165965afb1e8b0cdd59
JOURNAL_STREAM=8:582963
SYSTEMD_EXEC_PID=136271
{"level":"info","ts":1698070360.1823046,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
{"level":"warn","ts":1698070360.1842122,"logger":"caddyfile","msg":"Unnecessary header_up X-Forwarded-Host: the reverse proxy's default behavior is to pass headers to the upstream"}
{"level":"warn","ts":1698070360.1867957,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
Error: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 69.171.67.22:2019: bind: cannot assign requested address
caddy.service: Main process exited, code=exited, status=1/FAILURE
caddy.service: Failed with result 'exit-code'.

**Comment by ZacharyRen77** [comment]
same as you,do you fix it?

**Comment by ZacharyRen77** [comment]
even the IP is the same as you,do you fix it?

**Comment by yonggekkk** [comment]
先选择非编译方式吧
