### ISSUE TITLE
能加个自定义 DNS 解锁吗？

### ISSUE THREAD

**Issue by NeedforGit** [yonggekkk/NaiveProxy-yg#4]
勇哥好，这个脚本很好用，一直在用。但是貌似 Naiveproxy 不能自定义 dns 解锁网飞之类，勇哥能加上这个功能吗？

或者指点一下在 config 文件中 哪里能设置 自定义 dns?

感谢！

**Comment by yonggekkk** [comment]
不清楚……这个就不拓展了

**Comment by NeedforGit** [comment]
> 不清楚……这个就不拓展了

好吧，还是感谢勇哥！
