### ISSUE TITLE
ChatGPT解锁问题

### ISSUE THREAD

**Issue by sketchain** [yonggekkk/NaiveProxy-yg#7]
![image](https://github.com/user-attachments/assets/231c5726-3a24-4a8f-8a7a-5eccf35f1a51)
![image](https://github.com/user-attachments/assets/85c8281a-3443-437c-a46d-4559d8255f12)
![image](https://github.com/user-attachments/assets/861a627a-2652-463e-8af8-e30a3ded14cb)
![image](https://github.com/user-attachments/assets/ce03f473-355c-4bf7-b6d9-dce706c49735)
服务器能解锁 curl有回应 但客户端（小火箭）却不行 测速也是可以的 只有ChatGPT访问不了 别的都能打开

**Comment by yonggekkk** [comment]
Bug了！香港不支持gpt
