### ISSUE TITLE
监听端口有特殊要求吗？我随便填了一个监听端口，但连不通。

### ISSUE THREAD

**Issue by ssfeng72** [yonggekkk/NaiveProxy-yg#8]
监听端口有特殊要求吗？我随便填了一个监听端口，
![Screenshot_20240822-184530_NekoBox](https://github.com/user-attachments/assets/f6f503b6-aec8-41a6-ab3d-27134708faa1)
但连不通。

**Comment by yonggekkk** [comment]
随机就行
